import ProductCard from '../components/ProductCard';
import styles from '../styles/Menu.module.css';
import { getProducts } from './api/products/index';
import Head from 'next/dist/shared/lib/head';


const ShopPage = ({ products }) => {
    return(
        <div className={styles.container}>
            <Head>
        <title>shoplist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

            <h1 className={styles.title}>Result for All Menu</h1>
            <div className={styles.cards}>
               {products.map((product) =>(
                   <ProductCard key={product.id} product={product} />
               ))}
            </div>
        </div>
    );
};

export default ShopPage;

export async function getStaticProps(){
    const products = await getProducts();
    return { props : { products } };
}